### ISSUE TITLE
[Bug]: Importing Pipeline file Access Denied

### ISSUE THREAD

**Issue by manosnoam** [opendatahub-io/data-science-pipelines-operator#367] opened 2023-10-04 15:00 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

ODH Dashboard UI

### Version

RHODS 1.33 (V1)

### Environment

Managed Cluster on GCP

### Current Behavior

1) Importing this pipeline file by a cluster admin user (htpasswd-cluster-admin-user):
[iris-pipeline-compiled.zip](https://github.com/opendatahub-io/data-science-pipelines-operator/files/12804797/iris-pipeline-compiled.zip)

Fails with access denied error:
![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/9913945/599d825a-03a9-479a-8049-2dc9722a6909)

Note that the DS Project was created by a basic user (non-admin) originally, but it is accessible by the cluster admin user.

2) Retrying to upload the content again, using the same pipeline name ("noam pipeline 1"), is rejected as if the same pipeline name already exist (it isn't, since it failed creating that pipeline in previous step):

![image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/9913945/02a73d1b-5714-4418-acd9-363168d8d374)

### Expected Behavior

For Step 1) The import should go through, since we're importing with a cluster admin.
For Step 2) If the pipeline project was not created, the project name shouldn't have been there.

### Steps To Reproduce

See above.

**Comment by diegolovison** [comment] 2023-10-04 15:39
Can't replicate the issue

**Comment by jgarciao** [comment] 2023-10-04 16:36
Could the problem be that pipeline name has spaces?

**Comment by diegolovison** [comment] 2023-10-04 16:51
> Could the problem be that pipeline name has spaces?

No

**Comment by HumairAK** [comment] 2023-11-02 14:44
@gregsheremeta

**Comment by gregsheremeta** [comment] 2023-11-02 14:46
this is a duplicate of https://github.com/opendatahub-io/data-science-pipelines/issues/165

closing

**Closed by gregsheremeta** 2023-11-02 14:46 UTC
Labels: kind/bug, priority/normal, needinfo
