### ISSUE TITLE
[DSPv2] Investigate MLMD Connectivity issues

### ISSUE THREAD

**Issue by gmfrasca** [opendatahub-io/data-science-pipelines-operator#380] opened 2023-10-05 14:10 UTC
In the DSPv2 PoC, running a pipeline will stall for a few seconds and then display a vague error:

![Image](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/29403382/502fa96b-7786-4890-b90e-ab0ac9772832)

The error text is also not particularly useful but preliminary analysis seems to suggest it is an issue with connecting to an MLMD endpoint 

Error text:
`Cannot find context with {"typeName":"system.PipelineRun","contextName":"b3a3f2e3-abb5-4629-800f-27a25b516f56"}: Cannot find specified context`

**Comment by gregsheremeta** [comment] 2023-10-12 14:23
per @rimolive 's investigation in #369 this might actually be a duplicate of #369 

@gmfrasca to look into :)

**Closed** 2023-10-27 19:55 UTC
Labels: triage/accepted, v2-integration
