### ISSUE TITLE
[Bug]: "SSL connection errors" connecting to a Data Science Pipelines apiserver instance

### ISSUE THREAD

**Issue by gregsheremeta** [opendatahub-io/data-science-pipelines-operator#244] opened 2023-08-02 17:57 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Deploy type

ODH Dashboard UI

### Version

varies

### Environment

varies

### Current Behavior

We're encountered a few instances of people contacting us about components getting "SSL connection errors" when they try to connect to a Data Science Pipelines instance. I'm concerned that something is nebulously "not quite right" with the way the DSP apiserver is using TLS.

One report:
[RHODS-8860] Data Science Pipelines error "unable to get issuer certificate" on OSD cluster
https://issues.redhat.com/browse/RHODS-8860
For this one, QE tests passed on an OpenStack cluster, but the problem was seen on an OSD cluster, which uses a LetsEncrypt certifcate installed by the OSD infrastructure.

Another report:
"I've got a partner running into certification issues while submitting pipelines through Elyra. They're using a custom certificate in their OCP cluster, which seems to break the Data Science Pipelines integration. Has anyone encountered similar issues? Elyra requests to Data Science Pipelines fail with this error message:
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1129). Running RHODS self-managed 1.29.0 on OCP 4.11.44."

Developers for Elyra and Dashboard have worked around this problem by allowing insecure connections in the caller, but that is a sub-optimal solution -- we need to get to the bottom of this.

### Expected Behavior

In clusters with trusted certificates installed (e.g. LetsEncrypt), SSL connections to DSP apiserver from Dashboard, Elyra, or a laptop should all "just work" without needing to allow insecure connections or passing a custom certificate bundle to the client code.

In clusters with self-signed certificates installed, ???
 - for clients connecting to the DSP apiserver from outside the cluster, the client would need to allow insecure connections or be passed the signer's certificate
 - for pods running in the cluster, ??? - is there a way we can make these "just work" too?

### Steps To Reproduce

unknown

**Comment by gregsheremeta** [comment] 2023-08-02 17:58
related: https://github.com/opendatahub-io/notebooks/issues/159

**Comment by amadhusu** [comment] 2023-08-30 16:53
Seeing another case of this from the field will post their findings here once I receive the same.

**Comment by amadhusu** [comment] 2023-10-05 12:19
[https://github.com/opendatahub-io/data-science-pipelines-operator/issues/362](url) - This issue is also relevant to the topic being discussed here. I am working on a fix which might solve both the referenced and issue and this one. I will need to find a way test both the fixes once I am done.

**Comment by gregsheremeta** [comment] 2023-10-19 11:17
Investigated this a bit. Note this drawing

![Screenshot from 2023-10-17 07-33-23](https://github.com/opendatahub-io/data-science-pipelines-operator/assets/2248293/db0afcba-e6fd-4824-b10b-825360da8ad1)

This ticket is about the blue circle, whereas #362 is about the red circle. They will have different solutions.

**Comment by HumairAK** [comment] 2023-10-26 14:29
We should confirm whether this is a problem on dsp backend side

**Comment by gregsheremeta** [comment] 2023-11-02 18:51
We were seeing this on known good properly secured clusters -- specifically OSD, which plumbs in LetsEncrypt on the apps route. So this is not quite the same problem as the "use my self signed cert everywhere" problem. With LE properly on board the route, we were seeing both Elyra and Dashboard having TLS problems connecting to our route.

In the case where LE is on the route, neither Elyra nor Dashboard _should_ have a problem connecting to our route. The fact that they both do made me nervous that something was wrong with the DSP route, because the chances that Elyra and Dashboard both have to enable insecure connection to connect to the DSP route is fishy. The chance that they are both struggling to load the correct OS-level CA bundle from their respective container image bases seems pretty low.

**Comment by HumairAK** [comment] 2023-11-03 20:01
Okay so I tried taking a look at this and my conclusion is that this is not a DSP related issue. 

I reproduced this error by enabling tls verify in the node js server for odh dashboard [here](https://github.com/red-hat-data-services/odh-dashboard/blob/main/backend/src/routes/api/proxy/index.ts#L64). And deploying both DSP and ODH Dashboard on an hypershift cluster secured via LetsEncrypt, which is recognized by basically most major operating systems/browsers.

Let's understand this toggle: 

> rejectUnauthorized [<boolean>](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Data_structures#Boolean_type) If not false, the server certificate is verified against the list of supplied CAs. An 'error' event is emitted if verification fails; err.code contains the OpenSSL error code. Default: true. [source](https://nodejs.org/api/tls.html#tlsconnectoptions-callback)

As we all know, this field is disabled by odh-dashboard currently to bypass the current issue above which is not ideal. 

Technically we would expect connections from Dashboard -> Pipelines route to always work (even on self-signed certs), because we use Re-encrypt Routes. Which means the Dashboard pod default cert bundles should be able to validate the cert chains received from DSP route.

Indeed, if I curl the DSP route from the Dashboard pod from a LetsEncrypt secured OCP cluster I do not get any insecure tls errors :


Curl successful from ODH Dashboard pod to DSP pod:
```bash
sh-4.4$ curl -I --request GET "https://ds-pipeline-pipelines-definition-test.apps.rosa.greg-1102.kv5l.p3.openshiftapps.com/apis/v1beta1/runs"  -H "Authorization: Bearer <omited>"
HTTP/1.1 200 OK
content-length: 2
content-type: application/json
date: Fri, 03 Nov 2023 17:52:58 GMT
gap-auth: hukhan@redhat.com@cluster.local
gap-upstream-address: localhost:8888
grpc-metadata-content-type: application/grpc
set-cookie: 16569b7999b96e75b5553be61c12f275=c764d98e5e4250350bd87f7716e922e4; path=/; HttpOnly; Secure; SameSite=None
cache-control: private
```

If it was behind an unrecognized cert hitting the route would yield:

```bash
$ curl -I https://ds-pipeline-sample-dspa.apps.hukhan-3.dev.datahub.redhat.com/apis/v1beta1/runs -H "Authorization: Bearer <omitted>"
curl: (60) SSL certificate problem: self-signed certificate in certificate chain
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```
And I would need to enable curl's `--insecure` flag to disable tls verification and bypass this error, much like how odh-dashboard currently bypasses tls veri

So we know the odh-dashboard pod can indeed run rest calls against the DSP route with tls enabled. Then why do we see the error above only when running calls via odh dashboard proxy? 

Here I have no clear answers, but my hunch is the culprit is [here](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/directCallUtils.ts#L47). 

When making proxy calls this CA seems to be passed in as part of the `https.RequestOptions`, and I wonder if this is somehow forcing the request calls to ignore the well-known CAs shipped as part of the default pod bundles. I think this option is described [here](https://nodejs.org/api/tls.html#tlscreatesecurecontextoptions): 

> Default is to trust the well-known CAs curated by Mozilla. **Mozilla's CAs are completely replaced when CAs are explicitly specified using this option**. The value can be a string or Buffer, or an Array of strings and/or Buffers. Any string or Buffer can contain multiple PEM CAs concatenated together.....

I tried to mess around with the CAs being mounted here though and found little success, currently it seems the CA passed in is the same as the one found in `/var/run/secrets/kubernetes.io/serviceaccount`. If this is not the issue, I suspect it is the solution probably lies somewhere in how the TLS requests are being configured when proxy requests are being made.

**Comment by HumairAK** [comment] 2023-11-03 20:04
Before closing this out, I think it would be good to get an ack from dashboard team that this is dashboard side based on the above, if there's still opinions that this is a dsp issue we can continue pursuing / investigating this further. 


@andrewballantyne

**Comment by HumairAK** [comment] 2023-11-06 14:33
It is also worth mentioning currently Dashboard connects to DSP api server via an OCP `route` and not the internal svc A record, so traffic probably leaves the cluster then is routed back to the cluster. I think, if instead dashboard uses the internal A record to communicate with api server example something like `https://ds-pipeline-sample.dspa.svc.cluster.local:8443`, then the traffic would be kept internal and the insecure flag is not as big of a deal.

**Comment by gregsheremeta** [comment] 2023-11-06 14:51
> then the traffic would be kept internal and the insecure flag is not as big of a deal

I would encourage the dashboard team to remove the insecure flag, _especially_ if they change to connect to the `svc.cluster.local` URL instead of the route. Insecure should not be needed when connecting to `svc.cluster.local`

**Comment by HumairAK** [comment] 2023-11-10 03:44
Okay yeah think I've got it. It is indeed because of [this](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/directCallUtils.ts#L47). 

I believe dashboard can do the following to resolve this issue: 

1. Remove the ca being passed in [here](https://github.com/opendatahub-io/odh-dashboard/blob/main/backend/src/utils/directCallUtils.ts#L47). This will use the default well-known trusted CA's for proxy calls.
2. Re-enable `rejeactUnauthorized` [here](https://github.com/red-hat-data-services/odh-dashboard/blob/main/backend/src/routes/api/proxy/index.ts#L64)
3. Then set the following: 
```yaml
      env:
        - name: NODE_EXTRA_CA_CERTS
          value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
```
In the dashboard container [here](https://github.com/red-hat-data-services/odh-dashboard/blob/main/manifests/base/deployment.yaml#L29). For the self-signed portion.

This should allow dashboard to re-enable secure connections with dsp (and other public routes using well known trusted CA's). Using `NODE_EXTRA_CA_CERTS` _extends_ the well-known trusted CA's, whereas passing in the CA to `httpsRequest.request` will override them.

**Comment by HumairAK** [comment] 2023-11-10 03:45
fyi @andrewballantyne ^

**Closed** 2023-11-14 20:31 UTC
Labels: kind/bug, triage/accepted, priority/normal, field-priority
